
subscription_id     = ""
resource_group_name = ""
aks_cluster_name    = ""
cluster_type        = ""
kv_name             = ""
sync_provider       = "github"
sync_kind           = "GitRepository"
git_path            = ""
git_ref             = "refs/heads/main"
git_url             = ""
cluster_domain      = ""
cluster_size        = "small"
