
subscription_id     = ""
github_token        = ""
resource_group_name = ""
aks_cluster_name    = ""
cluster_type        = ""
kv_name             = ""
sync_provider       = ""
sync_kind           = ""
git_path            = ""
git_ref             = ""
git_url             = ""
cluster_domain      = ""
cluster_size        = ""
